


--SET search_path TO schema_nutri;

CREATE TABLE FACTOR_ZONA (
    CONGLOME INT,
    VIVIENDA INT,
    ID CHAR(4),
    COD_DOMINIO BIGINT,
    DOMINIO VARCHAR(255),
    COD_ETAPADEVIDA BIGINT,
    ETAPADEVIDA VARCHAR(255),
    RESULTADOFINALDELAENCUESTACompleta1Incompleta2Rehazo3Otros6 INT,
    UBIGEO BIGINT,
    DEPARTAMENTO VARCHAR(255),
    PROVINCIA VARCHAR(255),
    DISTRITO VARCHAR(255),
    PRIMARY KEY (CONGLOME, VIVIENDA, ID).
    FOREIGN KEY (CONGLOME, VIVIENDA, ID) REFERENCES GENERAL_001 (CONGLOME, VIVIENDA, ID)
);

\copy FACTOR_ZONA FROM '/Users/camilacode/Library/Mobile Documents/com~apple~CloudDocs/Ciclo 5/ACD/Proyecto/vianev-ninos-2017-2018_0/csv_sin_index/DATA_FACTOR.csv' DELIMITER ',' CSV HEADER;

--Completa1Incompleta2Rehazo3Otros6
CREATE TABLE GENERAL_001 (
    CONGLOME INT,
    VIVIENDA INT,
    HOGAR INT,
    ID CHAR(4),
    ETAPA_VIDA INT,
    ALTITUD INT,
    SEXO INT,
    DEPARTAMENTO VARCHAR(255),
    CCPP VARCHAR(255),
    PROVINCIA VARCHAR(255),
    DISTRITO VARCHAR(255),
    RES_PESO INT,
    RES_TALLA INT,
    RES_HB INT,
    RES_FINAL INT,
    PRIMARY KEY (CONGLOME, VIVIENDA, ID)
);


CREATE TABLE NECESIDADES_100 (
    CONGLOME INT,
    VIVIENDA INT,
    ID CHAR(4),
    P101 INT,
    P102 INT,
    P103 INT,
    P104 INT,
    P105 INT,
    P106 INT,
    P107 INT,
    P108 INT,
    P109 INT,
    P110 INT,
    P111 INT,
    P112 INT,
    P113_BICICLETA INT,
    P113_MOTOCICLETA INT,
    P113_CARRO INT,
    P113_OTRO INT,
    P111_TEL_FIJO INT,
    P111_TEL_CELULAR INT,
    P111_CABLE INT,
    P111_INTERNET INT,
    P112_RADIO INT,
    P112_TELEVISOR INT,
    P112_COMPUTADORA INT,
    P112_HORNO INT,
    P112_LAVADORA INT,
    P112_REFRIGERADORA INT,
    P112_COCINA INT,
    P112_PLANCHA INT,
    P112_EQUIPO INT,
    PRIMARY KEY (CONGLOME, VIVIENDA, ID),
    FOREIGN KEY (CONGLOME, VIVIENDA, ID) REFERENCES GENERAL_001 (CONGLOME, VIVIENDA, ID)
);

-- Crear tabla SEGURO_PS
CREATE TABLE SEGURO_PS (
    CONGLOME INT,
    VIVIENDA INT,
    ID CHAR(4), 
    P209 FLOAT,
    P210_PSOC_01 FLOAT,
    PRIMARY KEY (CONGLOME, VIVIENDA, ID),
    FOREIGN KEY (CONGLOME, VIVIENDA, ID) REFERENCES GENERAL_001 (CONGLOME, VIVIENDA, ID)
);

-- Crear tabla MICRONUTRIENTES_300
CREATE TABLE MICRONUTRIENTES_300 (
    CONGLOME INT,
    VIVIENDA INT,
    ID CHAR(4),
    P313_1_CONSUME_MMN INT,
    PRIMARY KEY (CONGLOME, VIVIENDA, ID),
    FOREIGN KEY (CONGLOME, VIVIENDA, ID) REFERENCES GENERAL_001 (CONGLOME, VIVIENDA, ID)
);


-- Crear tabla SUPLEMENTOS_300
CREATE TABLE SUPLEMENTOS_300 (
    CONGLOME INT,
    VIVIENDA INT,
    ID CHAR(4),
    P314_CONSUME_SUPL INT,
    P314_OBTUVO_SUPL FLOAT,
    P314_PRESENTA_SUPL FLOAT,
    P314_AYER FLOAT,
    P314_DIARIO FLOAT,
    PRIMARY KEY (CONGLOME, VIVIENDA, ID),
    FOREIGN KEY (CONGLOME, VIVIENDA, ID) REFERENCES GENERAL_001 (CONGLOME, VIVIENDA, ID)
);

-- Crear tabla ANEMIA_300
CREATE TABLE ANEMIA_300 (
    CONGLOME INT,
    VIVIENDA INT,
    ID CHAR(4),
    P306 INT,
    P307 INT,
    P311 INT,
    P312 INT,
    P313 INT,
    P320 INT,
    PRIMARY KEY (CONGLOME, VIVIENDA, ID),
    FOREIGN KEY (CONGLOME, VIVIENDA, ID) REFERENCES GENERAL_001 (CONGLOME, VIVIENDA, ID)
);

-- Crear tabla CRED_PESO_TALLA
CREATE TABLE CRED_PESO_TALLA (
    CONGLOME INT,
    VIVIENDA INT,
    ID CHAR(4),
    P325_PESO_NAC FLOAT,
    P327_PESO_00 FLOAT,
    P327_TALLA_00 FLOAT,
    P327_PESO_01 FLOAT,
    P327_TALLA_01 FLOAT,
    P327_PESO_02 FLOAT,
    P327_TALLA_02 FLOAT,
    P327_PESO_03 FLOAT,
    P327_TALLA_03 FLOAT,
    P327_PESO_04 FLOAT,
    P327_TALLA_04 FLOAT,
    P327_PESO_05 FLOAT,
    P327_TALLA_05 FLOAT,
    P327_PESO_06 FLOAT,
    P327_TALLA_06 FLOAT,
    P327_PESO_07 FLOAT,
    P327_TALLA_07 FLOAT,
    P327_PESO_08 FLOAT,
    P327_TALLA_08 FLOAT,
    P327_PESO_09 FLOAT,
    P327_TALLA_09 FLOAT,
    P327_PESO_10 FLOAT,
    P327_TALLA_10 FLOAT,
    P331 FLOAT,
    P332 FLOAT,
    P333 FLOAT,
    P334 FLOAT,
    PRIMARY KEY (CONGLOME, VIVIENDA, ID),
    FOREIGN KEY (CONGLOME, VIVIENDA, ID) REFERENCES GENERAL_001 (CONGLOME, VIVIENDA, ID)
);


-- Crear tabla EDUCACION_300
CREATE TABLE EDUCACION_300 (
    CONGLOME INT,
    VIVIENDA INT,
    ID CHAR(4),
    P336 INT,
    P337 FLOAT,
    P338 FLOAT,
    P339 FLOAT,
    P340 FLOAT,
    P341 FLOAT,
    P342 FLOAT,
    P343 FLOAT,
    P344 FLOAT,
    P345_TIEMPO VARCHAR,
    P345_MESES FLOAT,
    P345_DIAS FLOAT,
    P346 FLOAT,
    P347 FLOAT,
    P348 FLOAT,
    P349 FLOAT,
    P350 FLOAT,
    P351 FLOAT,
    P352 FLOAT,
    PRIMARY KEY (CONGLOME, VIVIENDA, ID),
    FOREIGN KEY (CONGLOME, VIVIENDA, ID) REFERENCES GENERAL_001 (CONGLOME, VIVIENDA, ID)
);

-- Crear tabla ALIMENTACION_300
CREATE TABLE ALIMENTACION_300 (
    CONGLOME INT,
    VIVIENDA INT,
    ID CHAR(4),
    P367 INT,
    P368_TIEMPO FLOAT,
    P368_HORAS FLOAT,
    P368_DIAS FLOAT,
    P369 FLOAT,
    P370_MESES FLOAT,
    P370_NS FLOAT,
    P371 INT,
    P371_AGUA INT,
    P371_FORMULA INT,
    P371_LECHE_ENVASADA INT,
    P371_LECHE_VACA INT,
    P371_JUGO INT,
    P371_OTRO INT,
    P371_CALDOS INT,
    P371_NINGUNO INT,
    PRIMARY KEY (CONGLOME, VIVIENDA, ID),
    FOREIGN KEY (CONGLOME, VIVIENDA, ID) REFERENCES GENERAL_001 (CONGLOME, VIVIENDA, ID)
);

-- Crear tabla RES_SIN_ID_400
CREATE TABLE RES_SIN_ID_400 (
    CONGLOME INT,
    VIVIENDA INT,
    ID CHAR(4),
    P400 INT,
    P402 INT,
    P408_EDAD INT,
    P408_AÑOS FLOAT,
    P408_MESES INT,
    P409 FLOAT,
    P410 FLOAT,
    P411 FLOAT,
    P412 FLOAT,
    P413 FLOAT,
    P415 FLOAT,
    P416_RES_PESO INT,
    P416_RES_TALLA INT,
    P416_RES_HB INT,
    PRIMARY KEY (CONGLOME, VIVIENDA, ID),
    FOREIGN KEY (CONGLOME, VIVIENDA, ID) REFERENCES GENERAL_001 (CONGLOME, VIVIENDA, ID)
);
